version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: library_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-library_pass}
      POSTGRES_DB: ${POSTGRES_DB:-library_db}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: library_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@library.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS:-admin123}
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - db

volumes:
  postgres_data:
