import { Injectable, Injector } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { RealtimeService } from './realtime.service';

export type Lang = 'en' | 'th';

@Injectable({
    providedIn: 'root'
})
export class LanguageService {
    private currentLang = new BehaviorSubject<Lang>((localStorage.getItem('lang') as Lang) || 'en');
    lang$ = this.currentLang.asObservable();
    private realtime?: RealtimeService;

    constructor(private injector: Injector) {
        // Use timeout and injector to avoid immediate circular dependency during init if any
        setTimeout(() => {
            this.realtime = this.injector.get(RealtimeService);
            this.realtime.messages$.subscribe(msg => {
                if (msg.event === 'LANGUAGE_CHANGED' && msg.payload?.lang) {
                    const newLang = msg.payload.lang as Lang;
                    if (newLang !== this.lang) {
                        this.setLang(newLang, false); // false to avoid rebroadcasting
                    }
                }
            });
        }, 0);
    }

    get lang(): Lang {
        return this.currentLang.value;
    }

    setLang(l: Lang, broadcast = true) {
        localStorage.setItem('lang', l);
        this.currentLang.next(l);

        if (broadcast && this.realtime) {
            this.realtime.send({
                event: 'LANGUAGE_CHANGED',
                payload: { lang: l }
            });
        }
    }

    toggleLang() {
        this.setLang(this.lang === 'en' ? 'th' : 'en');
    }

    translate(key: string): string {
        const l = this.lang;
        return translations[l][key] || key;
    }
}

export const translations: Record<Lang, Record<string, string>> = {
    en: {
        'nav.books': 'Books',
        'nav.categories': 'Categories',
        'nav.wallet': 'Wallet',
        'nav.payment': 'Payment',
        'nav.loans': 'Loans',
        'nav.inventory': 'Inventory',
        'nav.members': 'Members',
        'nav.profile': 'View Profile',
        'nav.signout': 'Sign Out',
        'nav.theme': 'Theme',
        'nav.lang': 'Language',
        'nav.clear_cache': 'Clear Cache',
        'home.welcome': 'Simplify your reading journey',
        'home.search_placeholder': 'Find books, authors, or categories...',
        'home.stats.books': 'Books available',
        'home.stats.categories': 'Categories',
        'home.stats.days': 'Day borrowing',
        'home.recommended': 'Recommended for You',
        'home.based_on_interests': 'Based on your interests',
        'home.update_interests': 'Update Interests',
        'home.new_arrivals': 'New Arrivals',
        'home.most_popular': 'Most Popular',
        'home.view_all': 'View All',
        'common.return': 'Return',
        'common.loading': 'Loading...',
        'common.no_records': 'No records found',
        'common.status': 'Status',
        'common.all': 'All',
        'common.active': 'Active',
        'common.returned': 'Returned',
        'common.overdue': 'Overdue',
        'common.anonymous': 'Anonymous',
        'common.days': 'days',
        'borrow.error_funds': 'Insufficient funds (Minimum 50.00 THB required)',
        'borrow.error_fines': 'You have unpaid fines. Please top up to settle them.',
        'borrow.error_unavailable': 'Book is currently unavailable',
        'borrow.error_already_borrowing': 'You are already borrowing this book',
        'borrow.success': 'Borrowed successfully!',
        'borrow.return_success': 'Returned successfully!',
        'borrow.btn': 'Borrow Book',
        'book.details': 'Book Details',
        'book.available': 'available',
        'book.unavailable': 'Unavailable',
        'book.borrowed': 'Borrowed',
        'book.return_date': 'Return Date',
        'book.description': 'Description',
        'book.views': 'Views',
        'book.borrows': 'Borrows',
        'book.year': 'Year',
        'book.publisher': 'Publisher',
        'profile.total': 'Total Borrows',
        'profile.debt': 'Debt',
        'profile.member_since': 'Member since',
        'profile.wallet_balance': 'Wallet Balance',
        'profile.pay_debt': 'Pay Debt',
        'wallet.title': 'Wallet',
        'wallet.balance': 'Balance',
        'wallet.topup': 'Top-up',
        'wallet.fines': 'Unpaid Fines',
        'wallet.history': 'Transaction History',
        'wallet.fine_rate': 'Fine Rate',
        'wallet.student': 'Student',
        'wallet.professor': 'Professor',
        'role.student': 'Student',
        'role.professor': 'Professor',
        'role.librarian': 'Librarian',
        'role.admin': 'Admin',
        'admin.users.title': 'Member Directory',
        'admin.users.sub': 'Manage and distinguish library members by their assigned roles',
        'admin.users.members': 'Students & Professors',
        'admin.users.staff': 'Staff (Librarians & Admins)',
        'admin.inventory.title': 'Inventory Control',
        'admin.inventory.sub': 'Monitor book availability, total stock, and library performance',
        'admin.inventory.status': 'Inventory Status',
        'admin.inventory.stats': 'Usage Stats',
        'admin.borrows.title': 'Management: Borrowing Records',
        'admin.borrows.sub': 'Monitor all active and past book loans across the library',
        'admin.borrows.active': 'Active Loans',
        'admin.borrows.all': 'All Records',
        'admin.notify.send': 'Send Message',
        'admin.notify.reason': 'Select Reason',
        'admin.notify.custom': 'Or write your own message...',
        'admin.notify.btn': 'Send Notification',
        'admin.notify.reason1': 'You have overdue books, please return them soon.',
        'admin.notify.reason2': 'Your debt has been outstanding for too long.',
        'admin.notify.reason3': 'Custom Message',
        'admin.notify.success': 'Notification sent!',
        'wallet.gateway.secured': 'Secured · 256-bit SSL',
        'wallet.gateway.amount': 'Top-up Amount',
        'wallet.gateway.card': 'Card',
        'wallet.gateway.promptpay': 'PromptPay',
        'wallet.gateway.transfer': 'Transfer',
        'wallet.gateway.card_number': 'Card Number',
        'wallet.gateway.card_holder': 'Cardholder Name',
        'wallet.gateway.card_expiry': 'Expiry',
        'wallet.gateway.card_cvv': 'CVV',
        'wallet.gateway.pp_hint': 'Scan QR with your banking app',
        'wallet.gateway.pp_step1': 'Open banking app',
        'wallet.gateway.pp_step2': 'Scan QR code above',
        'wallet.gateway.pp_step3': 'Confirm amount',
        'wallet.gateway.pp_step4': 'Click "Confirm Payment" below',
        'wallet.gateway.bank_name': 'Kasikorn Bank',
        'wallet.gateway.acc_name': 'Account Name',
        'wallet.gateway.acc_num': 'Account Number',
        'wallet.gateway.transfer_amt': 'Transfer Amount',
        'wallet.gateway.bank_hint': 'Transfer exactly the amount shown and send slip to admin within 24 hours',
        'wallet.gateway.processing': 'Processing...',
        'wallet.gateway.proc_verify': 'Verifying information',
        'wallet.gateway.proc_confirm': 'Confirming payment',
        'wallet.gateway.proc_wallet': 'Updating wallet',
        'wallet.gateway.success_title': 'Top-up Successful!',
        'wallet.gateway.success_sub': 'The amount has been added to your wallet',
        'wallet.gateway.ref_code': 'Reference Code',
        'wallet.gateway.close': 'Close',
        'wallet.gateway.secure_info': 'Data is encrypted with 256-bit SSL',
        'wallet.gateway.confirm_btn': 'Confirm Payment',
        'wallet.gateway.send_slip': 'Slip Sent',
        'wallet.topup.placeholder': 'Enter amount',
        'wallet.topup.btn': 'Top-up',
        'wallet.history.empty': 'No transaction history',
        'wallet.fine_rate.per_day': '฿ / day',
        'profile.email': 'Email',
        'profile.phone': 'Phone',
        'payment.title': 'Pay Fines',
        'payment.summary': 'Fine Summary',
        'payment.total_due': 'Total Due',
        'payment.no_fines': 'No outstanding fines',
        'payment.no_fines_sub': "You're all clear!",
        'payment.back_profile': 'Back to Profile',
        'wallet.error.insufficient': 'Insufficient funds in Wallet. Available: ฿{{balance}}, Required: ฿{{amount}}',
        'wallet.error.connection': 'Connection failed, please try again.',
        'wallet.error.generic': 'An error occurred',
        'wallet.history.topup': 'Top-up',
        'wallet.history.debt_settlement': 'Automatic Debt Settlement',
        'wallet.history.fine_payment': 'Fine Payment',
        'wallet.history.borrow_fee': 'Borrow Fee',
        'wallet.history.overdue_fine': 'Overdue Fine',
        'login.title': 'Sign In',
        'login.user': 'Username',
        'login.pass': 'Password',
        'login.btn': 'Sign In',
        'login.btn_loading': 'Signing in...',
        'login.no_acc': "Don't have an account?",
        'login.reg': 'Register',
        'login.err_fields': 'Please fill in all fields',
        'login.err_invalid': 'Invalid username or password',
        'register.title': 'Create Account',
        'register.role': 'Role',
        'register.name': 'Full Name',
        'register.email': 'Email',
        'register.pass': 'Password',
        'register.confirm': 'Confirm Password',
        'register.btn': 'Create Account',
        'register.btn_loading': 'Creating account...',
        'register.has_acc': 'Already have an account?',
        'register.signin': 'Sign in',
        'register.err_username_len': 'Username must be at least 3 characters',
        'register.err_pass_len': 'Password must be at least 6 characters',
        'register.err_pass_match': 'Passwords do not match',
        'interests.title': 'What are you interested in?',
        'interests.sub': 'Select at least 1 category to help us recommend the best books for you.',
        'interests.finish': 'Finish Setup',
        'interests.skip': 'Skip for now',
        'interests.err_save': 'Failed to save interests',
        'reco.title': 'Recommended for Your Interests',
        'reco.sub': 'Books we think you will love',
        'reco.empty': 'No recommendations yet. Try selecting more interests!'
    },
    th: {
        'nav.books': 'หนังสือ',
        'nav.categories': 'หมวดหมู่',
        'nav.wallet': 'กระเป๋าเงิน',
        'nav.payment': 'ชำระเงิน',
        'nav.loans': 'รายการยืม',
        'nav.inventory': 'คลังหนังสือ',
        'nav.members': 'สมาชิก',
        'nav.profile': 'โปรไฟล์',
        'nav.signout': 'ออกจากระบบ',
        'nav.theme': 'โหมดสี',
        'nav.lang': 'ภาษา',
        'nav.clear_cache': 'ล้างแคช',
        'home.welcome': 'เติมเต็มประสบการณ์การอ่านของคุณ',
        'home.search_placeholder': 'ค้นหาหนังสือ คนเขียน หรือหมวดหมู่...',
        'home.stats.books': 'หนังสือทั้งหมด',
        'home.stats.categories': 'หมวดหมู่หนังสือ',
        'home.stats.days': 'ระยะเวลาที่ยืมได้',
        'home.recommended': 'หนังสือแนะนำสำหรับคุณ',
        'home.based_on_interests': 'อ้างอิงจากความสนใจของคุณ',
        'home.update_interests': 'แก้ไขความสนใจ',
        'home.new_arrivals': 'หนังสือมาใหม่',
        'home.most_popular': 'หนังสือยอดนิยม',
        'home.view_all': 'ดูทั้งหมด',
        'common.return': 'ย้อนกลับ',
        'common.loading': 'กำลังโหลด...',
        'common.no_records': 'ไม่พบข้อมูล',
        'common.status': 'สถานะ',
        'common.all': 'ทั้งหมด',
        'common.active': 'กำลังยืม',
        'common.returned': 'คืนแล้ว',
        'common.overdue': 'เกินกำหนด',
        'common.anonymous': 'ไม่ระบุชื่อ',
        'borrow.error_funds': 'ยอดเงินในกระเป๋าไม่เพียงพอ (ต้องมีอย่างน้อย 50.00 บาท เพื่อยืมหนังสือ)',
        'borrow.error_fines': 'คุณมีค่าปรับค้างชำระ กรุณาเติมเงินเพื่อหักลบหนี้ก่อนยืมเพิ่ม',
        'borrow.error_unavailable': 'ขออภัย หนังสือเล่มนี้ไม่มีเล่มว่างในขณะนี้',
        'borrow.error_already_borrowing': 'คุณกำลังยืมหนังสือเล่มนี้อยู่แล้ว',
        'borrow.success': 'ยืมหนังสือสำเร็จ!',
        'borrow.return_success': 'คืนหนังสือสำเร็จ!',
        'borrow.btn': 'ยืมหนังสือ',
        'book.details': 'รายละเอียดหนังสือ',
        'book.available': 'เล่มที่ว่าง',
        'book.unavailable': 'หนังสือไม่ว่าง',
        'book.borrowed': 'ถูกยืมแล้ว',
        'book.return_date': 'กำหนดคืนหนังสือ',
        'book.description': 'คำอธิบาย',
        'book.views': 'ยอดเข้าชม',
        'book.borrows': 'ยอดการยืม',
        'book.year': 'ปีที่พิมพ์',
        'book.publisher': 'สำนักพิมพ์',
        'profile.total': 'ยอดการยืมทั้งหมด',
        'profile.debt': 'หนี้ค้างชำระ',
        'profile.member_since': 'เป็นสมาชิกตั้งแต่',
        'profile.wallet_balance': 'ยอดเงินในกระเป๋า',
        'profile.pay_debt': 'ชำระหนี้',
        'wallet.title': 'กระเป๋าเงิน',
        'wallet.balance': 'ยอดเงินคงเหลือ',
        'wallet.topup': 'เติมเงิน',
        'wallet.fines': 'ค่าปรับค้างชำระ',
        'wallet.history': 'ประวัติรายการ',
        'wallet.fine_rate': 'อัตราค่าปรับ',
        'wallet.student': 'นักศึกษา',
        'wallet.professor': 'อาจารย์',
        'admin.users.title': 'ทำเนียบสมาชิก',
        'admin.users.sub': 'จัดการและแยกแยะสมาชิกของห้องสมุดตามบทบาทที่ได้รับมอบหมาย',
        'admin.users.members': 'นักศึกษาและอาจารย์',
        'admin.users.staff': 'เจ้าหน้าที่ (บรรณารักษ์และผู้ดูแลระบบ)',
        'admin.inventory.title': 'ควบคุมคลังพัสดุ',
        'admin.inventory.sub': 'ตรวจสอบความพร้อมของหนังสือ ปริมาณหนังสือทั้งหมด และประสิทธิภาพของห้องสมุด',
        'admin.inventory.status': 'สถานะคลังหนังสือ',
        'admin.inventory.stats': 'สถิติการใช้งาน',
        'admin.borrows.title': 'การจัดการ: ประวิติการยืม',
        'admin.borrows.sub': 'ตรวจสอบหนังสือที่ถูกยืมอยู่และการยืมที่ผ่านมาทั้งหมดในห้องสมุด',
        'admin.borrows.active': 'กำลังถูกยืม',
        'admin.borrows.all': 'ประวัติทั้งหมด',
        'admin.notify.send': 'ส่งข้อความ',
        'admin.notify.reason': 'เลือกหัวข้อ',
        'admin.notify.custom': 'หรือเขียนข้อความเอง...',
        'admin.notify.btn': 'ส่งการแจ้งเตือน',
        'admin.notify.reason1': 'คุณยืมหนังสือเกินกำหนด',
        'admin.notify.reason2': 'คุณมียอดค้างชำระนานเกินไป',
        'admin.notify.reason3': 'เขียนข้อความเอง',
        'admin.notify.success': 'ส่งการแจ้งเตือนสำเร็จ!',
        'wallet.gateway.secured': 'ปลอดภัยด้วย SSL 256-บิต',
        'wallet.gateway.amount': 'จำนวนเงินที่เติม',
        'wallet.gateway.card': 'บัตรเครดิต',
        'wallet.gateway.promptpay': 'พร้อมเพย์',
        'wallet.gateway.transfer': 'โอนเงิน',
        'wallet.gateway.card_number': 'หมายเลขบัตร',
        'wallet.gateway.card_holder': 'ชื่อบนบัตร',
        'wallet.gateway.card_expiry': 'วันหมดอายุ',
        'wallet.gateway.card_cvv': 'รหัส CVV',
        'wallet.gateway.pp_hint': 'สแกน QR ด้วยแอปธนาคารของคุณ',
        'wallet.gateway.pp_step1': 'เปิดแอปธนาคาร',
        'wallet.gateway.pp_step2': 'สแกน QR Code ด้านบน',
        'wallet.gateway.pp_step3': 'ยืนยันยอดเงิน',
        'wallet.gateway.pp_step4': 'กดปุ่ม "ยืนยันการชำระ" ด้านล่าง',
        'wallet.gateway.bank_name': 'ธนาคารกสิกรไทย',
        'wallet.gateway.acc_name': 'ชื่อบัญชี',
        'wallet.gateway.acc_num': 'เลขที่บัญชี',
        'wallet.gateway.transfer_amt': 'ยอดที่ต้องโอน',
        'wallet.gateway.bank_hint': 'โอนตามยอดที่ระบุและส่งสลิปให้แอดมินภายใน 24 ชั่วโมง',
        'wallet.gateway.processing': 'กำลังดำเนินการ...',
        'wallet.gateway.proc_verify': 'ตรวจสอบข้อมูล',
        'wallet.gateway.proc_confirm': 'ยืนยันการชำระเงิน',
        'wallet.gateway.proc_wallet': 'เติมเงินเข้ากระเป๋า',
        'wallet.gateway.success_title': 'เติมเงินสำเร็จ!',
        'wallet.gateway.success_sub': 'ยอดเงินถูกเติมเข้า wallet เรียบร้อยแล้ว',
        'wallet.gateway.ref_code': 'รหัสอ้างอิง',
        'wallet.gateway.close': 'ปิด',
        'wallet.gateway.secure_info': 'ข้อมูลถูกเข้ารหัสปลอดภัย SSL 256-บิต',
        'wallet.gateway.confirm_btn': 'ยืนยันการชำระเงิน',
        'wallet.gateway.send_slip': 'ส่งสลิปแล้ว',
        'wallet.topup.placeholder': 'ระบุจำนวนเงิน',
        'wallet.topup.btn': 'เติมเงิน',
        'wallet.history.empty': 'ไม่พบประวัติการทำรายการ',
        'wallet.fine_rate.per_day': 'บาท / วัน',
        'profile.email': 'อีเมล',
        'profile.phone': 'เบอร์โทรศัพท์',
        'payment.title': 'ชำระค่าปรับ',
        'payment.summary': 'สรุปยอดค่าปรับ',
        'payment.total_due': 'ยอดที่ต้องชำระ',
        'payment.no_fines': 'ไม่มีค่าปรับค้างชำระ',
        'payment.no_fines_sub': 'ยินดีด้วย คุณไม่มีหนี้สินค้างชำระ!',
        'payment.back_profile': 'กลับไปยังหน้าโปรไฟล์',
        'wallet.error.insufficient': 'ยอดใน Wallet ไม่พอ มี ฿{{balance}} ต้องการ ฿{{amount}}',
        'wallet.error.connection': 'ไม่สามารถเชื่อมต่อได้ กรุณาลองใหม่',
        'wallet.error.generic': 'เกิดข้อผิดพลาด',
        'wallet.history.topup': 'เติมเงิน',
        'wallet.history.debt_settlement': 'หักหนี้ค้างชำระอัตโนมัติ',
        'wallet.history.fine_payment': 'จ่ายค่าปรับ',
        'wallet.history.borrow_fee': 'ค่ายืมหนังสือ',
        'wallet.history.overdue_fine': 'ค่าปรับเกินกำหนด',
        'login.title': 'เข้าสู่ระบบ',
        'login.user': 'ชื่อผู้ใช้งาน',
        'login.pass': 'รหัสผ่าน',
        'login.btn': 'เข้าสู่ระบบ',
        'login.btn_loading': 'กำลังเข้าสู่ระบบ...',
        'login.no_acc': 'ยังไม่มีบัญชีผู้ใช้?',
        'login.reg': 'สมัครสมาชิก',
        'login.err_fields': 'กรุณากรอกข้อมูลให้ครบทุกช่อง',
        'login.err_invalid': 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',
        'register.title': 'สร้างบัญชีใหม่',
        'register.role': 'บทบาท',
        'register.name': 'ชื่อ-นามสกุล',
        'register.email': 'อีเมล',
        'register.pass': 'รหัสผ่าน',
        'register.confirm': 'ยืนยันรหัสผ่านอีกครั้ง',
        'register.btn': 'สร้างบัญชี',
        'register.btn_loading': 'กำลังสร้างบัญชี...',
        'register.has_acc': 'มีบัญชีอยู่แล้ว?',
        'register.signin': 'เข้าสู่ระบบ',
        'register.err_username_len': 'ชื่อผู้ใช้งานต้องมีอย่างน้อย 3 ตัวอักษร',
        'register.err_pass_len': 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
        'register.err_pass_match': 'รหัสผ่านไม่ตรงกัน',
        'interests.title': 'คุณสนใจหนังสือแนวไหน?',
        'interests.sub': 'เลือกหมวดหมู่ที่คุณสนใจอย่างน้อย 1 หมวดหมู่ เพื่อให้เราแนะนำหนังสือที่เหมาะกับคุณ',
        'interests.finish': 'เสร็จสิ้นการตั้งค่า',
        'interests.skip': 'ข้ามไปก่อน',
        'interests.err_save': 'ไม่สามารถบันทึกความสนใจได้',
        'reco.title': 'หนังสือแนะนำสำหรับคุณ',
        'reco.sub': 'หนังสือที่เราคัดสรรมาให้ตามความสนใจของคุณ',
        'reco.empty': 'ยังไม่มีหนังสือแนะนำ ลองเลือกหมวดหมู่ที่สนใจเพิ่มดูนะครับ!',
        'role.student': 'นักศึกษา',
        'role.professor': 'อาจารย์',
        'role.librarian': 'บรรณารักษ์',
        'role.admin': 'ผู้ดูแลระบบ'
    }
};
